# Generated by Django 3.2.9 on 2021-11-15 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id_number', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('id_type', models.CharField(choices=[('PH', 'Física'), ('JU', 'Jurídica'), ('NI', 'Número de Identificación Tributario Especial'), ('DM', 'Documento de Identifcación de Migración y Extrangería')], default='PH', max_length=2)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('password_attempts', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('attended_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_professional', to='appointments.worker')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='appointments.patient')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretary', to='appointments.worker')),
            ],
        ),
    ]
