# Generated by Django 3.2.9 on 2021-11-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='id_type',
            field=models.CharField(choices=[('PH', 'Física'), ('JU', 'Jurídica'), ('NI', 'Número de Identificación Tributario Especial'), ('DM', 'Documento de Identifcación de Migración y Extranjería')], default='PH', max_length=2),
        ),
        migrations.AlterField(
            model_name='worker',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
